services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: UTC
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
volumes:
  mysql_data:
